<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="floor" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.2" /> <!-- Link 1 0.5-->
  <xacro:property name="height2" value="0.2" /> <!-- Link 2 0.3-->
  <xacro:property name="height3" value="0.2" /> <!-- Link 3 0.3-->
  <xacro:property name="height4" value="0.05" /> <!-- Link 4 -->
  <xacro:property name="width4" value="2" /> <!-- Link 4 -->
  <xacro:property name="limit_joint" value="0.26" /> <!-- Limit joint-->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find floor_description)/urdf/floor.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find floor_description)/urdf/floor_materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <!-- <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/> -->
    <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
    <limit effort="1000" lower="-${limit_joint}" upper="${limit_joint}" velocity="1.5" />
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <!-- <origin xyz="0 0 ${height2}" rpy="0 0 0"/> -->
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
      	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 ${height2}" rpy="0 0 0"/>
    <!-- <origin xyz="${width} 0 ${height2 - axel_offset*2}" rpy="0 0 0"/> -->
    <limit effort="1000" lower="-${limit_joint}" upper="${limit_joint}" velocity="1.5" />
    <axis xyz="1 0 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
      	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>


  <joint name="fixed_base" type="fixed">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${height3}" rpy="0 0 0"/>
  </joint>


    <!-- Base Link -->
  <link name="link4">
    <collision>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width4} ${width4} ${height4}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width4} ${width4} ${height4}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height4/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width4*width4 + height4*height4)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height4*height4 + width4*width4)}" iyz="0.0"
        izz="${mass / 12.0 * (width4*width4 + width4*width4)}"/>
    </inertial>
  </link>

  <link name="imu_link">
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-09" ixy="0.0" ixz="0.0" iyy="1e-09" iyz="0.0" izz="1e-09"/>
    </inertial>
  </link>
 
  <joint name="imu_joint" type="fixed">
    <parent link="link4" />
    <child link="imu_link" />
    <origin xyz="0 0 ${height4}" rpy="0 0 0"/>
  </joint>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
